### ISSUE TITLE
URL signature mismatch error

### ISSUE THREAD

**Issue by rainneh** [theus/instantgram#13] opened 2018-12-15 22:53 UTC
Hi,

I've been using [instantgram] occasionally on Safari on my MBP, and it works 100% of the time that I've used it.

However, pretty recently, every time I use the bookmarklet, it transfers me to a new tab with nothing but the text "URL signature mismatch"

I restarted my laptop and now it only works for a few photos, but for most posts I'm still receiving that error message.

Thanks for your time! I really love using the function of the bookmarklet; hope we can find a fix!

**Comment by theus** [comment] 2018-12-16 20:20
Thanks, @rainneh. Can you send me an Instagram post that not working and it's opening with "URL signature mismatch"?

**Comment by rainneh** [comment] 2018-12-17 03:10
Hey,

https://www.instagram.com/p/Bp1knG_g3ak/

Here's an example. I've tried deleting the bookmarklet and re-dragging it into my bookmarks, but it's still a little iffy for some posts.

I've noticed that it works more frequently with posts that have more than one photos in them.

**Comment by theus** [comment] 2018-12-19 00:44
Here it worked :(

I think can be a different version of Instagram (like explained in [this comment](https://github.com/theus/instantgram/issues/12#issuecomment-444701134)) or a different structure of URL (I don't know.... because of a different CDN?)

Using your link as example, I got this URL: https://instagram.fssa2-2.fna.fbcdn.net/vp/99005cd08b739c120470e81c7e4b58c7/5CA5B1AF/t51.2885-15/e35/43779110_715391632170484_1681788762310846298_n.jpg?_nc_ht=instagram.fssa2-2.fna.fbcdn.net

**Comment by nightputting** [comment] 2018-12-24 00:20
I am having the same "URL signature mismatch" error. But it is only for certain photos. Restarting the browser does not seem to help.

**Comment by theus** [comment] 2018-12-24 20:38
Before [instantgram] open the URL, it removes a part of URL that sets a small size (to always get an HD image). In some cases, throws this error. I think can be this the problem. But, fix this error and get small images?

**Comment by DoctorCandor** [comment] 2018-12-25 21:12
I went and inspected the picture element of a random post using Chrome, and just like you suspected it appears that Instagram has now switched to using a different structure of URL for the full resolution picture, so removing the part of the URL that sets a small size doesn't work anymore. The source URL is now listed inside a <img> element in the HTML with 640 width, 750 width, 1080 width, and source URLs all listed in there.

**Comment by DoctorCandor** [comment] 2018-12-25 21:13
I went and inspected the picture element of a random post using Chrome, and just like you suspected it appears that Instagram has now switched to using a different structure of URL for the full resolution picture, so removing the part of the URL that sets a small size doesn't work anymore. The source URL is now listed inside an `<img>` element in the HTML with 640 width, 750 width, 1080 width, and source URLs all listed in there.

**Comment by At-M** [comment] 2018-12-27 22:00
I've got the same issue (obviously) and it seems they sometimes increase their filename by one number in the middle.

(numbers below mean the amount of numbers between underscores)
before:
8_15_19_letter.jpg
now:
8_16_19_letter.jpg

**Comment by Maldark** [comment] 2018-12-27 22:04
Same issue here. Bookmarklet is version 3.0.0 and the instagram post in question is https://www.instagram.com/p/Br5cSEoh78A/

The source shows that the image URL is https://scontent-dus1-1.cdninstagram.com/vp/16298fc2d0559b1cf4c6a8b9518d9a40/5CBE0020/t51.2885-15/e15/47091962_324238431753918_575913810171473446_n.jpg?_nc_ht=scontent-dus1-1.cdninstagram.com but the bookmarklet opens the URL https://scontent-dus1-1.cdninstagram.com/vp/5aefc5575bf6004dfb0e7a0566dd0957/5CCA0E62/t51.2885-19/43705877_363688051039896_1591159343057731584_n.jpg?_nc_ht=scontent-dus1-1.cdninstagram.com

It is worth mentioning that some do work, for instance https://www.instagram.com/p/BryHWtsACVc/

**Comment by theus** [comment] 2018-12-28 01:56
In my browser, all of your links work well. As I said, I think that's because of a different version of CDN. I've tried some adjusts. In [instantgram] dev, the script logs the app object in `console.log`. [I hosted a version of [instantgram] DEV in jsfiddle](http://jsfiddle.net/theus/a9dcpy1q/1/embedded/result/). You guys can test this new bookmark and see the `console.log` output*?

_*open the console before run the bookmarklet_

**Comment by At-M** [comment] 2018-12-28 03:09
rainnehs link from 11 days ago seems to work fine with the "old" bookmarklet, Maldarks link from a few hours ago too.

This doesn't work for me with the "old" bookmarklet.
https://www.instagram.com/p/Br6gKl8hEY9/

The DEV Bookmarklet seems to open up a profilepicture of a person who liked the post.

Which part of the console do you need?
The firefox console puts out a lot of information

**Comment by duha59** [comment] 2018-12-28 04:05
https://www.instagram.com/p/Brk6QrPFUYB/
doesn't work

**Comment by Maldark** [comment] 2018-12-28 05:06
As At-M points out, it would be useful to know what parts of the console log output you're looking for. If we take the post I linked above as an example, using your new dev version opens an image, but it's the profile image of a mutual follower who has liked the post, not the actual post itself.

Looking into the log output, I see that the object being output has an array of images, where the aforementioned profile picture is at index 0, the actual image is at index 1 (although not at the highest resolution available) and the profile picture of NVIDIA (the author) at index 2.

For me the 3.0.0 bookmarlet works for both At-M's link and duha59's link. An annoying issue to debug indeed..

**Comment by VolenBE** [comment] 2018-12-28 15:11
> The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature. 


That's the error I got. 

Ho and I found something quite interesting. So if I do go in the "Application" tab in the developper tools of Chrome, then click on the 640x640px image I want full size then click on the 3.0 version of the bookmark I get the image full size.

**Comment by Orudeon** [comment] 2018-12-29 20:34
https://www.instagram.com/p/Br8G-rWB6HX/ This one has a URL mismatch with the stable 3.0, and the jsfiddle dev version gets the avatar of someone who liked the photo. The entire profile is full of photos that get URL Mismatches

**Comment by hsiehrobin** [comment] 2018-12-29 21:42
it looks like i get an error everytime there is someone who you follow also liking the photo
which is why when looking at some of the comments above, it works for some users and doesnt work for some. and @Maldark mentioned that it has to do with getting the index photo.

to debug this, find a photo on your account that has followers
for example, my attached image will show that 
![untitled](https://user-images.githubusercontent.com/3751085/50542307-53664f00-0b6f-11e9-87a3-e9bc48d348dd.png) i have friends that also liked this photo, and it will display the last profile picture in the three little bubble instead of the dailyhivevancouver photo

**Comment by rainneh** [comment] 2018-12-29 22:19
I find that for the photos on my IG feed, [instantgram] works perfectly fine for every photo, but it doesn't work anywhere else (photos on people's profiles, saved photos, etc. Even my own posts don't work).

**Comment by italomartinns** [comment] 2018-12-30 15:08
For some reason, stable 3.0.0 is working only if you open it in a private window or logout. Works fine on feed and stories, don't work in saved items or profiles except if you open it in a private window.

**Comment by Orudeon** [comment] 2018-12-30 17:47
Can confirm it works in a private window for... whatever reason. that's so weird

**Comment by theus** [comment] 2018-12-31 15:52
> rainnehs link from 11 days ago seems to work fine with the "old" bookmarklet, Maldarks link from a few hours ago too.
> 
> This doesn't work for me with the "old" bookmarklet.
> https://www.instagram.com/p/Br6gKl8hEY9/
> 
> The DEV Bookmarklet seems to open up a profilepicture of a person who liked the post.
> 
> Which part of the console do you need?
> The firefox console puts out a lot of information

![image](https://user-images.githubusercontent.com/61322/50563308-8b4dcd80-0cfa-11e9-9a64-5869d3d5f6cc.png)

`imageLinkBeforeParser` is an important item, because [instantgram] uses a simple regex to get a HD version of image and can generate a URL signature mismatch error

**Comment by theus** [comment] 2018-12-31 15:57
> rainnehs link from 11 days ago seems to work fine with the "old" bookmarklet, Maldarks link from a few hours ago too.
> 
> This doesn't work for me with the "old" bookmarklet.
> https://www.instagram.com/p/Br6gKl8hEY9/
> 
> The DEV Bookmarklet seems to open up a profilepicture of a person who liked the post.
> 
> Which part of the console do you need?
> The firefox console puts out a lot of information

This is another bug because Instagram added the feature (profile picture of a friend that liked) recently. And this can cause (and caused) a bug in [instantgram] search and I already put in issue https://github.com/theus/instantgram/issues/14

**Comment by theus** [comment] 2018-12-31 15:58
@At-M 
> The DEV Bookmarklet seems to open up a profilepicture of a person who liked the post.

This is another bug because Instagram added the feature (profile picture of a friend that liked) recently. And this can cause (and caused) a bug in [instantgram] search and I already put in issue #14

**Comment by theus** [comment] 2018-12-31 16:00
> For some reason, stable 3.0.0 is working only if you open it in a private window or logout. Works fine on feed and stories, don't work in saved items or profiles except if you open it in a private window.

So weird 😅. But I'll check this at tests

**Comment by TheShankar** [comment] 2019-01-01 20:53
I can confirm the theory that if somebody on your followers list, leaves a like on a photo you're trying to Instantgram, it gives the error.
I get this error "by hand" as well (editing the url myself)

Unfollowing the Friend and Trying to Get the Picture gives the correct result

**Comment by theus** [comment] 2019-01-08 11:38
Did you guys see that recently version of [instantgram] _resolved_ the bug of profile photo of a friend that liked the post? (#14 )

**Comment by TheShankar** [comment] 2019-01-08 19:33
Working perfectly now! Thank you Theus!

**Comment by theus** [comment] 2020-07-31 01:10
Issue resolved in [v3.0.1](https://github.com/theus/instantgram/releases/tag/v3.0.1)

**Closed as completed by theus** 2020-07-31 01:10 UTC
